# Generated by Django 4.0.1 on 2022-02-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armoire_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='avatar',
            field=models.ImageField(default='', upload_to='img/%y'),
        ),
    ]
