# Generated by Django 4.0.1 on 2022-02-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Armoire_app', '0002_piece_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='avatar',
            new_name='image',
        ),
    ]
