# Generated by Django 4.0.1 on 2022-02-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armoire_app', '0003_rename_avatar_piece_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='category',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Jumpsuit', 'Jumpsuit'), ('Accessories', 'Accessories')], default='Top', max_length=32),
        ),
        migrations.AlterField(
            model_name='piece',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Indigo', 'Indigo'), ('Violet', 'Violet'), ('Beige', 'Beige'), ('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Multi-Color', 'Multi-Color')], default='White', max_length=32),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
