# Generated by Django 4.0.1 on 2022-02-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armoire_app', '0004_alter_piece_category_alter_piece_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='category',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Onepiece', 'Onepiece'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')], default='Top', max_length=32),
        ),
        migrations.AlterField(
            model_name='piece',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Indigo', 'Indigo'), ('Violet', 'Violet'), ('Beige', 'Beige'), ('Tan', 'Tan'), ('White', 'White'), ('Black', 'Black'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Multi-Color', 'Multi-Color')], default='White', max_length=32),
        ),
    ]
